artifacts_root: artifacts

stage_01:
  root_dir: artifacts/data
  raw_data: artifacts/data/raw
  source_url: 'https://drive.google.com/file/d/1NWpTUUu9H1ukJ2n71lJnrGPdQQC-b_88/view?usp=sharing'
  zip_data: artifacts/data/raw/data.zip
  unzipped: artifacts/data/raw/mails/
  untarred: artifacts/data/extracted/
  numpytext: artifacts/data/numpy_text/

stage_02:
  root_dir: artifacts/data
  npy_data: artifacts/data/numpy_text/
  processed_data: artifacts/data/processed/

stage_03:
  root_dir: artifacts/models/
  training_data_spam: artifacts/data/processed/spam.npy
  training_data_ham: artifacts/data/processed/ham.npy

stage_04:
  root_dir: artifacts/models/
  model_path: artifacts/models/svm_model.joblib
  tfidf_vectorizer: artifacts/models/tfidf_vectorizer.joblib
